FROM alpine:latest
LABEL org.opencontainers.image.source=https://github.com/CBX0N/MetroNexus
ARG iptables-sidecar
RUN mkdir /rules
RUN apk add iptables
COPY ./entrypoint.sh entrypoint.sh
CMD ["sh", "entrypoint.sh"]