---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mediastack
  namespace: default
spec:
  install:
    createNamespace: true
  targetNamespace: mediastack
  interval: 30s
  chart:
    spec:
<<<<<<< HEAD
      chart: jellystack
=======
      chart: JellyStack
>>>>>>> e009388cb49998b1803e23db456c98e132c91294
      sourceRef:
        kind: HelmRepository
        name: cbxon-helm
        namespace: default
      interval: 30s