apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mediastack.name" . }}-jellyfin-deployment
  labels:
    {{- include "mediastack.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.jellyfin.replicaCount}}
  selector:
    matchLabels:
      {{- include "mediastack.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "mediastack.labels" . | nindent 8 }}
    spec:
      containers:
        - name: "{{ .Chart.Name }}"
          image: "{{ .Values.jellyfin.image }}"
          {{- with .Values.jellyfin.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.jellyfin.ports }}
          ports:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.jellyfin.env }}
          env:
            {{- toYaml . | nindent 12 }}
          {{end}}
          {{- with .Values.jellyfin.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
