---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: istio-base
  namespace: default
spec:
  install:
    createNamespace: true
  targetNamespace: istio-system
  interval: 10m
  chart:
    spec:
      chart: base
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: default
      interval: 10m
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: istio-istiod
  namespace: default
spec:
  install:
    createNamespace: true
  targetNamespace: istio-system
  interval: 10m
  chart:
    spec:
      chart: istiod
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: default
      interval: 10m
  dependsOn:
    - name: istio-base
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: istio-cni
  namespace: default
spec:
  install:
    createNamespace: true
  targetNamespace: istio-system
  interval: 10m
  chart:
    spec:
      chart: cni
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: default
      interval: 10m
  dependsOn:
    - name: istio-base
  values:
    profile: ambient
    cniConfDir: /var/lib/rancher/k3s/agent/etc/cni/net.d
    cniBinDir: /var/lib/rancher/k3s/data/current/bin/
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: istio-ztunnel
  namespace: default
spec:
  install:
    createNamespace: true
  targetNamespace: istio-system
  interval: 10m
  chart:
    spec:
      chart: ztunnel
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: default
      interval: 10m
  dependsOn:
    - name: istio-base