---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: istio-base
  namespace: default
spec:
  install:
    createNamespace: true
  targetNamespace: istio-system
  interval: 10m
  chart:
    spec:
      chart: base
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: default
      interval: 10m
